run new test

diff --git a/.github/workflows/test-integration.yml b/.github/workflows/test-integration.yml
--- a/.github/workflows/test-integration.yml
+++ b/.github/workflows/test-integration.yml
@@ -146,13 +146,32 @@ jobs:
       #   run: |
       #     forge script test/integration/workflows/GroupingIntegration.t.sol:GroupingIntegration --rpc-url=${{ env.RPC_URL }} -vvv --broadcast --priority-gas-price=1 --legacy --skip-simulation >> test-results.log
 
-      - name: Run LicenseAttachmentIntegration Tests
-        run: |
-          forge script test/integration/workflows/LicenseAttachmentIntegration.t.sol:LicenseAttachmentIntegration --rpc-url=${{ env.RPC_URL }} -vvv --broadcast --priority-gas-price=1 --legacy --skip-simulation >> test-results.log
+      # - name: Run LicenseAttachmentIntegration Tests
+      #   run: |
+      #     forge script test/integration/workflows/LicenseAttachmentIntegration.t.sol:LicenseAttachmentIntegration --rpc-url=${{ env.RPC_URL }} -vvv --broadcast --priority-gas-price=1 --legacy --skip-simulation >> test-results.log
 
-      - name: Run RegistrationIntegration Tests
+      - name: Run LicenseAttachmentIntegration Tests
+        id: license_attachment_test
+        continue-on-error: true
         run: |
-          forge script test/integration/workflows/RegistrationIntegration.t.sol:RegistrationIntegration --rpc-url=${{ env.RPC_URL }} -vvv --broadcast --priority-gas-price=1 --legacy --skip-simulation >> test-results.log
+          forge script test/integration/workflows/LicenseAttachmentIntegration.t.sol:LicenseAttachmentIntegration --rpc-url=${{ env.RPC_URL }} -vvv --broadcast --priority-gas-price=1 --legacy --skip-simulation > license_attachment_test.log
+  
+      - name: Check LicenseAttachmentIntegration Results and Append Log
+        run: |
+          cat license_attachment_test.log >> test-results.log
+          if [[ "${{ steps.license_attachment_test.outcome }}" == "failure" ]]; then
+            if grep -q "SUCCESS: Correctly reverted when exceeding the token limit." license_attachment_test.log; then
+              echo "✅ Transaction failed as expected. Continuing workflow."
+              exit 0
+            else
+              echo "❌ Transaction failed with an unexpected error."
+              exit 1
+            fi
+          fi
+
+      # - name: Run RegistrationIntegration Tests
+      #   run: |
+      #     forge script test/integration/workflows/RegistrationIntegration.t.sol:RegistrationIntegration --rpc-url=${{ env.RPC_URL }} -vvv --broadcast --priority-gas-price=1 --legacy --skip-simulation >> test-results.log
 
       # - name: Run RoyaltyIntegration Tests
       #   run: |
